// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDA4AyVqJx6SUuSGZw-TF8o_FIZrs_P_l0',
    appId: '1:1050230330137:web:adf8a225f2e38ac4efab88',
    messagingSenderId: '1050230330137',
    projectId: 'newbiestate-57f33',
    authDomain: 'newbiestate-57f33.firebaseapp.com',
    databaseURL: 'https://newbiestate-57f33-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'newbiestate-57f33.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzhIH6YPlOsDOD0K1PEJE9J0DVMxGQfkQ',
    appId: '1:1050230330137:android:beef4a91ca0fe4a4efab88',
    messagingSenderId: '1050230330137',
    projectId: 'newbiestate-57f33',
    databaseURL: 'https://newbiestate-57f33-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'newbiestate-57f33.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIUjF1wh4MCGKTX-rBKCEtdpTyzKinLps',
    appId: '1:1050230330137:ios:f02e9bb0e878c399efab88',
    messagingSenderId: '1050230330137',
    projectId: 'newbiestate-57f33',
    databaseURL: 'https://newbiestate-57f33-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'newbiestate-57f33.appspot.com',
    iosBundleId: 'com.example.newbieState',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIUjF1wh4MCGKTX-rBKCEtdpTyzKinLps',
    appId: '1:1050230330137:ios:b1d9ce0b115e4cf9efab88',
    messagingSenderId: '1050230330137',
    projectId: 'newbiestate-57f33',
    databaseURL: 'https://newbiestate-57f33-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'newbiestate-57f33.appspot.com',
    iosBundleId: 'com.example.newbieState.RunnerTests',
  );
}
